INSERT INTO t_book (book_name, author, publisher) VALUES ('80歳の壁', '和田秀樹', '幻冬舎');
INSERT INTO t_book (book_name, author, publisher) VALUES ('人は話し方が9割', '永松茂久', 'すばる舎');
INSERT INTO t_book (book_name, author, publisher) VALUES ('ジェイソン流お金の増やし方', '厚切りジェイソン', 'ぴあ');
INSERT INTO t_book (book_name, author, publisher) VALUES ('20代で得た知見', 'F', 'KADOKAWA');
INSERT INTO t_book (book_name, author, publisher) VALUES ('同志少女よ、敵を撃て', '逢坂冬馬', '早川書房');
INSERT INTO t_book (book_name, author, publisher) VALUES ('メシアの法', '大川隆法', '幸福の科学出版');
INSERT INTO t_book (book_name, author, publisher) VALUES ('898ぴきせいぞろい!ポケモン大図鑑（上・下）', '', '小学館');
INSERT INTO t_book (book_name, author, publisher) VALUES ('70歳が老化の分かれ道', '和田秀樹', '詩想社');
INSERT INTO t_book (book_name, author, publisher) VALUES ('本当の自由を手に入れる お金の大学', '両＠リベ大学長', '朝日新聞出版');
INSERT INTO t_book (book_name, author, publisher) VALUES ('私が見た未来 完全版', 'たつき諒', '飛鳥新社');
INSERT INTO t_book (book_name, author, publisher) VALUES ('TOEIC L&R TEST 出る単特急 金のフレーズ', 'TEX加藤', '朝日新聞出版');
INSERT INTO t_book (book_name, author, publisher) VALUES ('WORLD SEIKYO vol.3', '聖教新聞社', '聖教新聞社');
INSERT INTO t_book (book_name, author, publisher) VALUES ('ネイティブなら12歳までに覚える 80パターンで英語が止まらない!', '塚本亮', '高橋書店');
INSERT INTO t_book (book_name, author, publisher) VALUES ('WORLD SEIKYO vol.2', '聖教新聞社', '聖教新聞社');
INSERT INTO t_book (book_name, author, publisher) VALUES ('聖域', 'コムドット やまと', 'KADOKAWA');
INSERT INTO t_book (book_name, author, publisher) VALUES ('パンどろぼう', '柴田ケイコ', 'KADOKAWA');
INSERT INTO t_book (book_name, author, publisher) VALUES ('マスカレード・ゲーム', '東野圭吾', '集英社');
INSERT INTO t_book (book_name, author, publisher) VALUES ('パンどろぼうとなぞのフランスパン', '柴田ケイコ', 'KADOKAWA');
INSERT INTO t_book (book_name, author, publisher) VALUES ('だるまさんが', 'かがくいひろし', 'ブロンズ新社');
INSERT INTO t_book (book_name, author, publisher) VALUES ('呪術廻戦（18）', '芥見下々', '集英社');
INSERT INTO t_book (book_name, author, publisher) VALUES ('SPY×FAMILY（9）', '遠藤達哉', '集英社');
INSERT INTO t_book (book_name, author, publisher) VALUES ('ONE PIECE（101）', '尾田栄一郎', '集英社');
INSERT INTO t_book (book_name, author, publisher) VALUES ('東京卍リベンジャーズ（25）', '和久井健', '講談社');
INSERT INTO t_book (book_name, author, publisher) VALUES ('僕のヒーローアカデミア（33）', '堀越耕平', '集英社');
INSERT INTO t_book (book_name, author, publisher) VALUES ('怪獣8号（5）', '松本直也', '集英社');
INSERT INTO t_book (book_name, author, publisher) VALUES ('キングダム（64）', '原泰久', '集英社');
INSERT INTO t_book (book_name, author, publisher) VALUES ('HUNTER×HUNTER（37）', '冨樫義博', '集英社');
INSERT INTO t_book (book_name, author, publisher) VALUES ('ミステリと言う勿れ（10）', '田村由美', '小学館');
INSERT INTO t_book (book_name, author, publisher) VALUES ('転生したらスライムだった件（19）', '伏瀬', '講談社');